baseURL = "https://p-ortega.github.io/"
title = "Pablo Ortega Tong"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Pablo Ortega Tong"
description = "Geoscience, numerical model, coding and more .."
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = ["Pablo"]
images = "/static"
DateFormat = "2 January 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"
  disableFingerprinting = true

  [params.label]
  text = "Pablo Ortega Tong"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Dispersivity"
  subtitle = "Hey there! ðŸ‘‹ I'm Pablo, a geoscientist who loves sharing awesome stuff I've tried and stumbled on. On this website, you'll find cool things related to solute and reactive transport, numerical modelling, Python and coding goodies, and even some random rants. Oh, and don't be surprised if you catch a glimpse of shameless self-promotion too!"
  imageUrl = "2D_disper.gif"
  imageWidth = 200
  imageHeight = 200
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "about"
    url = "about"

    [[params.profileMode.buttons]]
    name = "tags"
    url = "tags"
    
    [[params.profileMode.buttons]]
    name = "posts"
    url = "posts"

  [params.homeInfoParams]
  Title = "Hi there ðŸ‘‹ I'm Pablo"
  Content = "Welcome to my personal website"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/portega_t"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/portega"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/p-ortega"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[markup.highlight]
noClasses = false

[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]
